###회원가입
POST http://localhost:4000/register
Content-Type: application/json; charset=UTF-8

{
  "user_id": "1234",
  "nickname": "chan",
  "password": "1234",
  "name": "hyck",
  "birth": "1990-01-01",
  "phonenum": "01067058085",
  "email": "1234@naver.com"
}