###회원가입15.165.117.176
POST http://localhost:4000/register
Content-Type: application/json; charset=UTF-8

{
  "user_id": "1234",
  "nickname": "qqqq",
  "password": "1234",
  "name": "qqqq",
  "birth": "1990-01-01",
  "phonenum": "01067058085",
  "email": "qqqq@naver.com"
}

###로그인15.165.117.176
POST http://15.165.117.176:4000/login
Content-Type: application/json; charset=UTF-8

{
  "id": "1234",
  "pw": "1234"
}

###이메일 인증코드 발송
POST http://localhost:4000/email
Content-Type: application/json; charset=UTF-8

{
  "email": "ri7116@naver.com"
}

###id찾기
post http://15.165.117.176:4000/find-id
Content-Type: application/json; charset=UTF-8

{
  "email": "qqqq@naver.com"
}

### 이메일 중복 체크 
post http://15.165.117.176:4000/check-id
Content-Type: application/json; charset=UTF-8

{
  "user_id": "1234"
}

###비밀번호 찾기
POST http://localhost:4000/reset-pw
Content-Type: application/json; charset=UTF-8

{
  "user_id": "1234",
  "email": "qqqq@naver.com",
  "newPassword":"1234",
  "confirmPassword":"1234"
}

###
POST https://w94yrmif2m.execute-api.ap-northeast-2.amazonaws.com/prod/login
Content-Type: application/json; charset=UTF-8

{
  "id": "1234",
  "pw": "1234"
}

### 별자리 조회(아이디 기반반)
GET http://15.165.117.176:4000/stars/1234/regions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQiLCJpYXQiOjE3Mzg3NjYwOTAsImV4cCI6MTczODgwMjA5MH0.z23L9I1urVBFIM8zBSo5YLzLQLcwhir1NKMhFwXujds
Content-Type: application/json

### 별자리 이름 설정 변경 및 여행한 별들 추가
PATCH http://15.165.117.176:4000/stars/name
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQiLCJpYXQiOjE3Mzg3NjYwOTAsImV4cCI6MTczODgwMjA5MH0.z23L9I1urVBFIM8zBSo5YLzLQLcwhir1NKMhFwXujds
Content-Type: application/json

{
  "name": "두번째별별"
}

### 별자리 랭킹 조회
GET http://15.165.117.176:4000/stars/ranking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQiLCJpYXQiOjE3Mzg3NjYwOTAsImV4cCI6MTczODgwMjA5MH0.z23L9I1urVBFIM8zBSo5YLzLQLcwhir1NKMhFwXujds
Content-Type: application/json

### 투표
POST http://15.165.117.176:4000/stars/vote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQiLCJpYXQiOjE3Mzg3NjYwOTAsImV4cCI6MTczODgwMjA5MH0.z23L9I1urVBFIM8zBSo5YLzLQLcwhir1NKMhFwXujds
Content-Type: application/json; charset=UTF-8

{
  "stars_id": 2,
  "post_user_id": "1" 
}
